pipeline:

  build:
    image: golang
    commands:
      - go build -o main

  publish:
    image: plugins/docker
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    repo: r.3r1.co/gowebapp
