language: go

sudo: required

services:
  - docker

script: go build -o main

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" r.3r1.co
  - docker build -t r.3r1.co/honratha/gowebapp .
  - docker push r.3r1.co/honratha/gowebapp

notifications:
  email: false
