language: go
sudo: required
services:
- docker
addons:
  ssh_known_hosts: 46.38.251.201
env:
- DOCKER_IMAGE_NAME="r.3r1.co/honratha/gowebapp:$TRAVIS_BUILD_NUMBER"
script: go build -o main
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" r.3r1.co
- docker build -t $DOCKER_IMAGE_NAME .
- docker push $DOCKER_IMAGE_NAME
before_deploy:
- openssl aes-256-cbc -K $encrypted_d3751784d1e2_key -iv $encrypted_d3751784d1e2_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
- provider: script
  script: ssh root@46.38.251.201 'docker pull $DOCKER_IMAGE_NAME && docker service
    update --image $DOCKER_IMAGE_NAME passwordservice'
before_install:
- openssl aes-256-cbc -K $encrypted_d3751784d1e2_key -iv $encrypted_d3751784d1e2_iv
  -in deploy_rsa.enc -out deploy_rsa -d
